#
---
eureka:
  instance:
    hostname: localhost
    port: 8010
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
 
---
spring:
  profiles: eureka
server:
  port: ${eureka.instance.port}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
