---
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
 
---
spring:
  profiles: eureka
server:
  port: 8010
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
